import { ArrowUpRight, Check, CreditCard, LayoutGrid, Link2, Search, Smartphone, Users, Webhook, Workflow } from 'lucide-react';

export function ServiceArtwork({ id }: { id: string }) {
  if (id === 'web-ecommerce') return <div className="detail-art detail-art-commerce" aria-hidden="true"><div className="art-window"><div className="art-browser"><span/><span/><span/><i>tu-tienda.com</i></div><div className="art-store-nav"><strong>FORMA<span>®</span></strong><small>Productos &nbsp; Nosotros &nbsp; Contacto</small><span>Bolsa (2)</span></div><div className="art-store-body"><div><small>HECHO PARA DESTACAR</small><strong>Una experiencia<br/><em>que convierte.</em></strong><span>Explorar colección <ArrowUpRight size={13}/></span></div><div className="art-product"><div className="art-product-shape"/><small>NUEVA COLECCIÓN</small></div></div></div><div className="art-payment"><CreditCard size={17}/><span>Pago integrado</span><Check size={15}/></div></div>;
  if (id === 'apps-software') return <div className="detail-art detail-art-app" aria-hidden="true"><div className="art-dashboard"><aside><strong>be<span>✳</span></strong><span className="active"><LayoutGrid size={13}/> Resumen</span><span>Proyectos</span><span>Equipo</span><span>Reportes</span></aside><div className="art-dashboard-main"><div className="art-dashboard-top"><span>Espacio de trabajo</span><span>●</span></div><strong>Todo en un lugar.</strong><small>Una vista clara de lo que importa.</small><div className="art-metrics"><div><span>En curso</span><strong>08</strong></div><div><span>Por revisar</span><strong>03</strong></div></div><div className="art-progress"><span>Proyecto digital <b>72%</b></span><i/></div></div></div><div className="art-phone"><Smartphone size={17}/><span>Web + móvil</span></div></div>;
  if (id === 'ui-ux') return <div className="detail-art detail-art-design" aria-hidden="true"><div className="art-design-canvas"><div className="art-design-title"><span>01 / DESCUBRIR</span><span>02 / DISEÑAR</span><span>03 / VALIDAR</span></div><div className="art-wireframes"><div><i/><strong/><span/><span/><span/></div><div><i/><strong/><span/><span/><span/></div><div><i/><strong/><span/><span/><span/></div></div><div className="art-design-footer"><span>De la idea a una experiencia clara.</span><span>↗</span></div></div></div>;
  if (id === 'seo-geo') return <div className="detail-art detail-art-search" aria-hidden="true"><div className="art-search-card"><div className="art-search-input"><Search size={17}/><span>¿Cómo te encuentran?</span><span>↵</span></div><div className="art-search-result"><small>RESULTADO ORGÁNICO</small><strong>Contenido útil. Estructura clara.</strong><span>Una respuesta que lleva a la página adecuada.</span></div><div className="art-search-result muted"><small>EXPERIENCIAS CON IA</small><strong>La misma base: información confiable.</strong><span>Sin atajos ni promesas de posicionamiento.</span></div></div></div>;
  return <div className="detail-art detail-art-integrations" aria-hidden="true">
    <span className="art-integrations-label"><Link2 size={12}/> INTEGRACIONES</span>
    <div className="art-integration-hub">
      <span className="hub-flow hub-flow-a"/><span className="hub-flow hub-flow-b"/><span className="hub-flow hub-flow-c"/><span className="hub-flow hub-flow-d"/>
      <div className="hub-node node-a"><span className="hub-node-status"/><CreditCard size={22}/><span>Pagos</span></div>
      <div className="hub-node node-b"><span className="hub-node-status"/><Users size={22}/><span>CRM</span></div>
      <div className="hub-node node-center"><span className="hub-node-pulse"/><Workflow size={33}/><strong>bebrand</strong></div>
      <div className="hub-node node-c"><span className="hub-node-status"/><LayoutGrid size={22}/><span>Datos</span></div>
      <div className="hub-node node-d"><span className="hub-node-status"/><Webhook size={22}/><span>API</span></div>
    </div>
  </div>;
}
